### ISSUE TITLE
drivers/misc/hwid

### ISSUE THREAD

**Issue by ccccoisini** [Xiaomi-Diting-Development/android_kernel_xiaomi_diting#1]
Hi, I'm trying to compile the official Xiaomi kernel narble-s-oss and I get the following error

scripts/Makefile.clean:15: drivers/misc/hwid/Makefile: No such file or directory
make[3]: *** No rule to make target 'drivers/misc/hwid/Makefile'.  Stop.
make[2]: *** [scripts/Makefile.clean:71: drivers/misc/hwid] Error 2
make[1]: *** [scripts/Makefile.clean:71: drivers/misc] Error 2
make: *** [Makefile:1945: _clean_drivers] Error 2

I would like to ask you, where can I download the file drivers/misc/hwid?

**Comment by Laulan56** [comment]
pick from my repo,you need to decompile to find the code of marble in hwid
